### ISSUE TITLE
DbAdapter = DbAdapter.MySql ignored

### ISSUE THREAD

**Issue by jeffsurcess** [jbogard/Respawn#116]
I'm getting a Microsoft.Data.SqlClient.SqlException when trying to perform a Respawner.CreateAsync action as below:

```
            var respawnerOptions = new RespawnerOptions
            {
                DbAdapter = DbAdapter.MySql
            };
            _respawner = await Respawner.CreateAsync(_connectionString, respawnerOptions);
```

For some reason respawner attempts to make a SQLServer connection; however nowhere in the project is SQLServer used.

Version: Respawn 6.0.0

**Comment by MrDave1999** [comment]
I think the problem is this line of code: https://github.com/jbogard/Respawn/blob/master/Respawn/Respawner.cs#L27

**Comment by jbogard** [comment]
Yeah that’s it, I can throw an exception in that case. That overload only supports SQL Server.On Feb 19, 2023, at 9:37 AM, Dave Roman ***@***.***> wrote:﻿
I think the problem is this line of code: https://github.com/jbogard/Respawn/blob/master/Respawn/Respawner.cs#L27

**Comment by jochem4207** [comment]
Any news on this? It's breaking the adapter functionality :(

**Comment by L968** [comment]
Here's how I managed to work around this issue:

    MySqlConnection connection = new MySqlConnection(ConnectionString);
    connection.Open();
    
    _respawner = await Respawner.CreateAsync(connection, new RespawnerOptions
    {
        DbAdapter = DbAdapter.MySql
    });

**Comment by jochem4207** [comment]
> MySqlConnection connection = new MySqlConnection(ConnectionString);
> connection.Open();
> 
> _respawner = await Respawner.CreateAsync(connection, new RespawnerOptions
> {
>     DbAdapter = DbAdapter.MySql
> });

Thank you! This indeed seems to fix the connection. My tests still failing due duplicate or not existing records. But that's probably a different issue
