### ISSUE TITLE
6.0.1 Release?

### ISSUE THREAD

**Issue by VelvetToroyashi** [jbogard/Respawn#118]
👋 Whilst using the library I stumbled upon failing tests. Upon further investigation, I found out it was [this issue](https://github.com/jbogard/Respawn/issues/104) which was fixed with [this PR](https://github.com/jbogard/Respawn/pull/105), which was merged in November. However the [latest release](https://github.com/jbogard/Respawn/releases/tag/v6.0.0) is dated in *September* (seven months ago!)

The former is a somewhat niche, but somewhat critical bugfix, as well as all the other improvements that've been added in the last 6-7 months. I wanted to inquire about the release of the next version?

**Comment by jbogard** [comment]
Done
