### ISSUE TITLE
Make implicit dependencies explicit

### ISSUE THREAD

**Issue by hulvei3** [jbogard/Respawn#16]
The project have an implicit dependency to `System.Data`, which could easily be added to the nuspec file. The dependencies is then automatically fetched from nuget.

The actual dependency should be [**System.Data.Common**](https://www.nuget.org/packages/System.Data.Common/4.0.0/)

In newer projects (and .NET Core projects) you might not have a machine dependency to System.\* assemblies anymore (and shouldn't)

**Comment by jbogard** [comment]
Fixed.
