### ISSUE TITLE
Persist the checkpoint

### ISSUE THREAD

**Issue by dbones** [jbogard/Respawn#17]
Hi

Is there a way to persist the checkpoint (the database with a known set of data), similar to nDbUnit (but without any manual need to create a xsd like file).

if not, please consider this a feature request 👍 

want to be able to check-in the persisted file, into source code along with component/service tests. this will allow for test runners (inc CI server, or tester) to use their own db (which may have no data or tables present)

**Comment by jbogard** [comment]
What would be in the checkpoint? Data? Schema? Both?

**Comment by dbones** [comment]
good question, apologies for my comment on tables, i can manage else where.

Data is the main goal.

possibly:

private static Checkpoint checkpoint = new Checkpoint
{
    SchemasToInclude = new []
    {
        "public"
    },
    DataSource = new PersistedCheckpoint("/location/in/repo")
};

**Comment by jbogard** [comment]
Is it a problem where the entire database is blank? The way we do this is our databases, both test and develop, run through Roundhouse to get created. Roundhouse allows for environment-specific scripts, so this is where we have test data. Finally, we tell Respawn to ignore those tables.

Does that make sense?

**Comment by dbones** [comment]
apologies for the delayed response.

yes it does. thank-you for the great tool(s).
