### ISSUE TITLE
Opening the Solution in VS 2015 Causes Projects not to Load

### ISSUE THREAD

**Issue by jjm340** [jbogard/Respawn#22]
Here are the errors I get when trying to open the solution in VS2015:

...\Respawn\Respawn.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\jmiller\Source\Repos\Respawn\Respawn\Respawn.csproj

...\Respawn.Tests\Respawn.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\jmiller\Source\Repos\Respawn\Respawn.Tests\Respawn.Tests.csproj

**Comment by jbogard** [comment]
Don't open in VS 2015. I migrated to VS 2017 and SDK-style projects.
