### ISSUE TITLE
Feature request: Provide ability to ignore specific relationships

### ISSUE THREAD

**Issue by mattbrooks2010** [jbogard/Respawn#24]
Would it be possible to add functionality to allow specific relationships to be ignored, in order to allow Respawn to be used when the database schema contains circular table relationships? This would be useful in test cases where the relationships causing the circular dependencies aren't relevant.

Some considerations:

- How would the relationships be specified - by foreign key constraint name?
- When would the relationships be specified - at checkpoint creation or during reset?

---

Related:
https://jimmybogard.com/respawn-vs-sql-server-snapshots/#comment-3552291593

**Comment by jbogard** [comment]
Sure, PRs are welcome.

The best way to handle this would be to detect them; and do the
disable/re-enable constraints for those specific relationships.

**Comment by mattbrooks2010** [comment]
Thanks. My employer allocates company time to working on open source software, so if this is something we can start work on, we'll update this issue.

**Comment by rick-moneybox** [comment]
Trying to introduce respawn into a project and we also have the issue with circular relationships - Did you make any progress on this @mattbrooks2010?
