### ISSUE TITLE
Cannot access Databases via Adminer

### ISSUE THREAD

**Issue by Jeern** [jbogard/Respawn#29]
Hi,

I have tried and tried and tried. Your unittests works fine, the Adminer tool starts too, after running docker-compose up -d and accessing localhost:8080, but no matter what I do I cannot make Adminer access neither MySql nor PostGres. 

Have you actually had the Adminer tool work in this configuration ?

For instance spying on your MySql unittests connectionstring I enter 

Server = 127.0.0.1:8082
User = root
Password = testytest
Database = MySqlTests

But I get SQLSTATE[HY000] [2002] Connection refused - I even tried to disable my firewall.

As mentioned I have tried every other configuration known to man. Is it supposed to work ?

**Comment by jbogard** [comment]
The first port is the external one and the second internal. Admirer uses
the internal one.

**Comment by Jeern** [comment]
Thank you. As mentioned I have tried every possible configuration. 127.0.0.1:3306 is one of them. Nothing works. :( I assume your comment means that it works on your machine ? Weird. I would prefer to make the Firebird Adapter from a working baseline.

**Comment by jbogard** [comment]
If you open a PR I can try locally. I can connect to the Postgres and MySQL
instances tho.

**Comment by Jeern** [comment]
OK, thank you I will do that eventually, but I am somewhat stubborn so I will try a bit more - It would be so cool if it worked :) I wonder if you have some prerequisite installed that you are not even aware of. On the other hand the tests work on my machine, so the databases must be running.  Only Adminer cannot access them, is it possible that you tell me what you enter in each login box for Postgres and MySQL ?
Server = ...
User = ...
Password = ...
Database = ...

**Comment by Jeern** [comment]
Using DataGrip from Jetbrains I could access the database with these settings:
Host: 0.0.0.0  Port: 8082 (3306 not working !)
User: root
Password: testytest
Database: MySqlTests

The exact same settings does not work with Adminer.

**Comment by jbogard** [comment]
That makes sense - Adminer connects internally through the Docker-created network. Externally, you'd only be able to access through the host port.

**Comment by Jeern** [comment]
Yeah. You are right. Makes sense. :) But doesn't make sense that Adminer does not work, I have tried on two different PC's (both Windows 10 64 bit) . Again could you tell me what you use for 
Server = ...
User = ...
Password = ...
Database = ...
To make it work on your PC ?

Just trying to help - I assume you are interested in this working for every contributor :)  And instead of me wasting a lot of time trying to help with this problem and you wasting time answering it would be nice if you just provide the settings for me to settle once and for all if this is a problem on your machine, my machine(s) or the docker-compose file.  Of course as mentioned I have already tried:
Server = 127.0.0.1:3306
User = root
Password = testytest
Database = MySqlTests

So that is not a winning combo. :)

**Comment by jbogard** [comment]
System: `PostgreSQL`
Server: `postgres-db`
User: `docker`
Password: `Password12!`

or

System: `MySQL`
Server: `mysql-db`
User: `root`
Password: `testytest`

That's how to connect through Adminer, which connects *inside* the Docker container network. The `Server` name comes from the service name in the `docker-compose.yml` file.

In order to connect via my tests (which don't execute inside a container) I have to [expose those services](https://docs.docker.com/compose/networking/) to the outside via the `HOST_PORT` part. Internally it uses the `CONTAINER_PORT` which I left as the defaults, that way I don't have to put those in via Adminer.

Does that help?

**Comment by Jeern** [comment]
Yeah sure. You're the man :) That worked ! It was the server part I couldn't guess - I have never seen the docker-compose syntax but in the manuals I saw for Adminer with Docker - Localhost/127.0.0.1 was used with portnumber. Therefore I guessed "mysql-db" was the db name until I saw you used "MySqlTests" in the tests then I just thought "mysql-db" was an identifier. I assume its obvious ? (to everyone but me). If not you could choose to write it in the readme. Anyway now the baseline works for me too and I can get on with it. Thank you... :)

**Comment by Jeern** [comment]
:) Then I would probably add it to the readme.md if  I were you though it might be like explaining a foreach statement to a lot of C# experts :) I don't know.

**Comment by jbogard** [comment]
Feel free to fix it in your PR!

**Comment by Jeern** [comment]
Fine will do :)

**Comment by jbogard** [comment]
Closed due to inactivity.

**Comment by Jeern** [comment]
You may think this is inactive but it is not, in fact I worked on it as late as last night. The problem is that the Adminer Image does not provide Firebird access, so I had to add it. But that means basing the Adminer Docker image on Debian instead of Alpine, so I have been working on a fork of that Github repo, in order to be able to continue work on this PR. It is ok to close this issue though :) I still hope to send you a PR some time in the future. BTW. I saw you in NDC London - good talk.

**Comment by bermudezc** [comment]
just for mysql use the name off container in server   ex:
docker run --name xx -d mysql

in adminer:
System: MySQL
Server: xx
User: root
Password:
