### ISSUE TITLE
Using Respawn for databases with "complex" relationships

### ISSUE THREAD

**Issue by thiagomajesk** [jbogard/Respawn#32]
Hi, I'd like to know if anyone here is using Respawn for testes using "real world" databases.
What I mean by that is that Respawn seems to work only with simple schemas - where we don't have lots of relationships between entities.

> Respawn examines the SQL metadata intelligently to build a deterministic order of tables to delete based on foreign key relationships between tables. It navigates these relationships to build a DELETE script starting with the tables with no relationships and moving inwards until all tables are accounted for.

For me, It doesn't seem that it's acting intelligently at all. When I try to restore the database after inserting `Foo` it calls me out about `Bar` and `Baz`:

>There is a dependency involving the DB tables [...] and we can't safely build the list of tables to delete.

A simplistic sample of the schema would be:

```c#
class Foo 
{
  int? BarId { get; set;}
}

class Bar
{
  ICollection<Foo> Foos { get; set; }
}

class Baz
{
  int? Foo { get; set; }
}
```

Same as: https://github.com/jbogard/Respawn/issues/12. In those cases, what would be the solution?

**Comment by jbogard** [comment]
So what you're really referring to is circular references, right? In terms of "real world" we use it on all of our projects, some with in the hundreds of tables so I'm not sure what qualifies "real world" or not.

The example you have doesn't show a circular reference though. If you want to deal with circular references, you'll need to ignore those tables and use FK disabling to do so (disable FKs, truncate tables, enable FKs).

Although I've seen quite a few "real world" databases that have zero referential integrity, and Respawn won't work for them of course.

**Comment by thiagomajesk** [comment]
Hi @jbogard, thanks for the prompt reply...
> So what you're really referring to is circular references, right?

Not only (but that's why I've linked Issue: #12). As you have already noticed, the example I provided can't be handled by Respawn, and It is not clear to me why.

> In terms of "real world" we use it on all of our projects, some with in the hundreds of tables so I'm not sure what qualifies "real world" or not.

That's a really good indicator to me.

> The example you have doesn't show a circular reference though. If you want to deal with circular references, you'll need to ignore those tables and use FK disabling to do so (disable FKs, truncate tables, enable FKs).

This seems a lot to ask from a test setup point of view, don't you think? Couldn't Respawn provide some built-in solution for those cases? 

PS.: I think would be great to have documentation for some common use cases like this

**Comment by jbogard** [comment]
No I actually don’t know what’s wrong with your original example. It
doesn’t show anything to me that Respawn can’t handle.

And I suppose it could handle those situations, but for our projects we let
Respawn handle just about everything and stuff it can’t we add another
custom step.

**Comment by jbogard** [comment]
Support for complex circular dependencies now in 3.0
