### ISSUE TITLE
Cannot delete rows from a temporal history table

### ISSUE THREAD

**Issue by OpenWindow** [jbogard/Respawn#33]
SQL server 2016 supports temporal tables. When calling `Reset `on `Checkpoint `results in error because you cannot directly delete rows from history table while `SYSTEM_VERSIONING = ON`.

**Comment by jbogard** [comment]
PR? I don't have a project using temporal tables.

What would the solution be here?

**Comment by OpenWindow** [comment]
I would like to work on it and submit a PR if you think this is a valid issue. 
Possible solution: Find if a table has a temporal table and set `SYSTEM_VERSIONING = OFF` for it. After delete, reset `SYSTEM_VERSIONING = ON`

**Comment by jbogard** [comment]
Sounds good!

**Comment by jbogard** [comment]
And no, it doesn't have to work for all database types. But it sounds like for some databases, you'd want some way to query additional metadata (see #38 ) and perform custom actions based on that.

**Comment by dozmus** [comment]
@jbogard Any reason why this was not merged in? I am in need of this feature.

**Comment by jbogard** [comment]
@dozmus  Check the PR, it has conflicts and unresolved feedback

**Comment by dozmus** [comment]
I'm happy to wrap this PR up if that's okay with you. I've locally fixed the merge conflicts, and have the tests passing.
Your comment about automatic detection was already fixed by the OP.

**Comment by dozmus** [comment]
@jbogard see #60
