### ISSUE TITLE
Postgres truncation performance can be greatly improved

### ISSUE THREAD

**Issue by sandord** [jbogard/Respawn#39]
I have a 51-table database that takes 13.5 seconds to clear (on Windows, in a Linux Docker container I see similar results), even if it is empty already.

After inspecting the `DeleteSql`, I found the following:

    ALTER TABLE "public"."table1" DISABLE TRIGGER ALL;
    ALTER TABLE "public"."table2" DISABLE TRIGGER ALL;
    truncate table "public"."table1" cascade;
    truncate table "public"."table2" cascade;
    ALTER TABLE "public"."table1" ENABLE TRIGGER ALL;
    ALTER TABLE "public"."table2" ENABLE TRIGGER ALL;

After some experimentation with the Postgres docs (https://www.postgresql.org/docs/9.1/static/sql-truncate.html) at hand. I found that the following is much faster:

    ALTER TABLE "public"."table1" DISABLE TRIGGER ALL;
    ALTER TABLE "public"."table2" DISABLE TRIGGER ALL;
    truncate table "public"."table1", truncate table "public"."table2";
    ALTER TABLE "public"."table1" ENABLE TRIGGER ALL;
    ALTER TABLE "public"."table2" ENABLE TRIGGER ALL;

The `cascade` option is not necessary in this case since the truncation of the tables is done in a single `truncate` statement.

It 'only' took 2.5 seconds, which is over 5 times faster!

I think it is still rather slow for a database with 51 tables that are already empty but at least it'd be a lot faster this way than it is at the moment.

**Comment by sandord** [comment]
> The cascade option is not necessary in this case since the truncation of the tables is done in a single truncate statement.
I don't know where I got that from but I don't think it's true. 
I do wonder however why it would be necessary to specify `cascade` because I reckon all tables are truncated anyway?

**Comment by seanfisher** [comment]
Looks like cascade was added in #3.

**Comment by jbogard** [comment]
Is it not needed then? The whole point was to get the order right.

**Comment by onimoger** [comment]
Not a Postgres pro, so can't comment on cascade necessity, but in general Postgres performance is extremely slow, bordering on unusable. I decided against using this library when each single test runs for ~4 seconds, cleaning up to 10 tables (other tables are in ignore list).
Same tests with transactions take milliseconds.

**Comment by sandord** [comment]
From the Postgres docs:

> TRUNCATE cannot be used on a table that has foreign-key references from other tables, unless all such tables are also truncated in the same command.

My guess is that when specifying all tables in a single `truncate` command, there is no need to specify `cascade` and even the trigger disabling/re-enabling commands aren't required anymore.

Maximum statement length shouldn't be a problem either (https://dba.stackexchange.com/a/131425/4327) so I think it's safe to put all tables in a single statement, regardless of the number of tables.

**Comment by sandord** [comment]
In the meantime I've found out that dropping and recreating the database using Postgres' `CREATE DATABASE dbname TEMPLATE template;` feature (https://www.postgresql.org/docs/9.3/static/manage-ag-templatedbs.html) is _much_ faster than anything else.

I'm using a database with structure but no data as the template database. This runs in about half a second on my machine, using a 52 table database with a few dozens of rows in each table.

**Comment by jbogard** [comment]
PR?

**Comment by sandord** [comment]
Sure, I'd like to do one. But first we might want to agree if the following is acceptable:

- We'll be creating an additional database (the template database is in fact a regular database) as a snapshot.
- We'll have to close existing connections (including the current connection) because otherwise, Postgres doesn't allow dropping/creating the database (reading the template database also doesn't work when connections to it exist).
- We'll have to connect to the system database (`postgres`) to perform the drop/create operations since no connection must exist to the template database. This requires connection string manipulation (change the database name in it) or the requirement of a second connection string that connects to the system database.

I hope this doesn't deviate too much from Respawn's concept.

**Comment by jbogard** [comment]
I’m just surprised this method is so fast. In SQL server it’s slooooow.

**Comment by jbogard** [comment]
I’m for whatever is fastest per database, but I can’t speak to the
connection requirements as to if that’s normal or OK in the PGSQL world.

**Comment by sandord** [comment]
Well, in the Postgres world I think we'll just have to accept that decent respawning speed comes with the connection requirements. I guess that in testing scenarios that shouldn't be much of an issue anyway.

If we make it an optional toggle, it could at least be helpful to a portion of Postgres users.

**Comment by sandord** [comment]
I was thinking about this a little more and I figured we're going to have to compare metadata between the current db and the template db.

This is because we'll need to be able to determine whether the template db is still a valid candidate for substitution of the current db. The structure of the current db might have changed (due to a migration or for whatever reason), rendering the template db obsolete so we definitely need a mechanism to determine whether the template db is still up to date.

Comparing metadata hashes is the most relyable way I can think of right now. I hope it doesn't come with a significant performance penalty though.

Here's the logic flow I'm thinking of:

	- If the template db doesn't exist
		○ If the current db has data
			§ Remove data from the current db
		○ Copy the current db as the template db
	- Else, if the template db exists
		○ If the current db has data
			§ Compare the current db and template db metadata
			§ If the metadata matches
				□ Copy the template db onto the current db
			§ Else, if the metadata doesn't match
				□ Remove data from the current db
				□ Copy the current db onto the template db
Use the current db

**Comment by sandord** [comment]
While sifting through my code, I found a requirement: the `dblink` Postgres extension. It allows the execution of a query in a remote database, which we'll need to perform operations such as creating the template database if it doesn't exist and dropping the template database before recreating it.

I started to feel a little worried about the requirements and other possible impact. This made me decide to write a terse impact assessment first, to see if it's worth the trouble. Note that it is based on a working implementation of this technique, implemented in one of my current projects.

## Impact
- We'll probably need a main switch on `Checkpoint`, something like `EnableCacheDatabaseCreation`. _Cache database_ sounds like the proper term to me since that's what it really is about: caching the reset operation result to improve performance.
- The `dblink` Postgres extension will be required.
- Since we don't want a dependency on something like Npgsql, we can't easily build a connection string that connects to the system (`pgsql`) database so we'll probably have to take in a system connection string which will have to be provided by the library consumer. It could be called `Checkpoint.SystemDatabaseConnectionString` or something. The consumer could decide to use Npgsql to create the system connection string, which is a simple three statement operation.
- We're going to have to close existing connections when dropping and copying databases. This means that when using `Checkpoint.Reset(DbConnection connection)`, the supplied connection will be closed at a certain point.
- By closing existing connections, any open connections in the ADO.NET connection pool will be corrupted by this operation. So, we'll have to reset the connection pool as well.
- The DbAdapters can decide whether to support cache database creation.

I have to say that I feel that there's just a little too much trickery going on to integrate this in Respawn nicely. I'm particularly worried about the closing of existing connections and resetting the connection pool. In my project, all of this is not a problem but that's just one project.

Looking at the current code base, I feel that the proposed functionality doesn't really fit in nicely. The abstractions will probably be polluted to some degree with stuff that perhaps will only apply to Postgres ever. 

Maybe it's a better idea to build a new library that depends on Respawn, targeting Postgres only.

I'd greatly value your opinion on this!

**Comment by jbogard** [comment]
Respawn.Postgres?

**Comment by sandord** [comment]
https://github.com/sandord/Respawn.Postgres. I haven't tested it thoroughly yet but this should be very close to its final state.

**Comment by sandord** [comment]
By the way, Respawn could still benefit from the `truncate table "public"."table1", truncate table "public"."table2";` approach, effectively making the intial `Reset` call on Respawn.Postgres quite a bit faster. Of course, the fastest performance can be expected from subsequent calls which kicks in the caching mechanism.

**Comment by sandord** [comment]
I'd like to comment on my approach (https://github.com/sandord/Respawn.Postgres) briefly, hoping for some feedback.

I deliberately did not inherit from `Checkpoint` because I felt that the `DataAdapter` property didn't have a place in a Postgres-only implementation. Additionally, the overloads of `Reset` taking a `DbConnection` weren't appropriate either due to the connection closing that is going on.

**Comment by sandord** [comment]
Alright, I've tested [Respawn.Postgres](https://github.com/sandord/Respawn.Postgres) some more and published it to NuGet ([Respawn.Postgres on NuGet](https://www.nuget.org/packages/Respawn.Postgres/)). Please keep in mind that it currently is marked as a prerelease.

I'd like to get some positive feedback before I remove the prerelease flag so please let me know if it works okay for you.

**Comment by sandord** [comment]
The [NuGet Package](https://www.nuget.org/packages/Respawn.Postgres/) is public.

**Comment by sandord** [comment]
https://github.com/jbogard/Respawn/pull/58 has shown great performance improvement for Postgres! 

Therefore, this issue can be closed.
