### ISSUE TITLE
Other scenarios? 

### ISSUE THREAD

**Issue by alexdresko** [jbogard/Respawn#4]
Why limit Respawn to only deleting data within tables? It seems like it'd be easy to have a flag that would tell a checkpoint to delete the tables instead of the data. This would work better for some of my projects where we use EF code first migrations to not only create tables, but insert and massage data as well. 

For that matter, I have C# code in other projects that goes as far as to delete and recreate a database using a SQL create script... and still in other projects, I detach and reattach databases instead. 

Have you considered taking Respawn to that level?

**Comment by Gilligan128** [comment]
This is not a likely scenario. See Jimmys blog post http://lostechies.com/jimmybogard/2013/06/18/strategies-for-isolating-the-database-in-tests/
For why this only deletes data and not any schema.

**Comment by alexdresko** [comment]
I don't understand what you mean by "not a likely scenario". There are plenty of comments in Jimmy's original Respawn post to back my claim that simply deleting data is not the only scenario. 

If inserting/massaging data in an Entity Framework migration was not a likely scenario, they wouldn't have made it an option in Entity Framework. :)

**Comment by ChrisMissal** [comment]
Just my two cents:

If you want something to manage migrations, creations, inserts, deletes, etc. Respawn could be added into a larger library as a dependency. I've been using the approach that this is based on for a few years now and it works well with [RoundhousE](https://github.com/chucknorris/roundhouse). The only thing mentioned that I haven't been able to do with these two libraries is the detach/reattach, but I've never tried that either.

**Comment by jbogard** [comment]
I'm limiting Respawn to deleting data from tables because that's the only approach I use these days. If I need a different scenario, I'll add it, but thanks for the request!
