### ISSUE TITLE
Master is not in NuGet

### ISSUE THREAD

**Issue by bubavanhalen** [jbogard/Respawn#42]
Hi, 

I saw that 3 commits currently are in the master branch, but not yet available in the NuGet package. 
This forces us to use a custom built dll and add it to the repo, which is really ugly. 

Would it be possible to Release 3.0.2 with the reseed functionality.

Thanks in advance.

**Comment by jbogard** [comment]
https://www.myget.org/feed/Details/respawn-ci

I push out releases about every 3 months to let the API changes settle.
