### ISSUE TITLE
SQL Injection - by design ?

### ISSUE THREAD

**Issue by Jeern** [jbogard/Respawn#43]
Hi, I have finally gotten back to writing the Pull Request for Firebird. I was sidetracked for a long time by Adminer not playing along with Firebird. I finally succeeded with that, and have gotten around to coding the firebird adapter.

But I immediately started feeling a bit dirty :) Now I know it is probably a non-issue since Respawn is only meant to be used from Tests, but still I wonder why you have opened it up to SQL injection. I am talking about the BuildTableCommandText for instance. Where you build the SQL as a string.

How about returning SQL + Parameters instead - in a Tuple for instance ? Or will it be too cumbersome ?

**Comment by jbogard** [comment]
SQL Injection from where now?

**Comment by Jeern** [comment]
Well, Stopping SQL injection is so ingrained in most developers mind that we almost automatically notice the potential problem and so I did with your code. Knowing your reputation I am 99,99 % sure that you did it on purpose, because it was easiest, and because actually it is not a problem technically if you use Respawn as intended.

But I see two issues with this.

1. Experienced developers are OK, but young developers looking at your code might think this is a valid approach to use in their own code.

2. If Respawn is not used as intended. Let me give you a good example. If you use Event Sourcing with CQRS it is perfectly valid to delete your readmodels (often Tables in a relational database) and rebuild them from the events. This is done even in production. Now, what better way to delete these tables than using Respawn. And often you want to be specific about which tables to delete. Then why not build a web service, sending a parameter directly to Respawns Exclude array. And boom - SQL injection possible... :)

I think I will just code the Firebird Adapter as the rest of the adapters, but raise a flag about this, that you or someone else might want to fix it some day. 

Another option would be to document it in the code where it happens and on the Exclude/include arrays.
