### ISSUE TITLE
Deletion Table Content

### ISSUE THREAD

**Issue by Jeern** [jbogard/Respawn#44]
As I am implementing the Firebird Adapter I have noticed that you disable all foreign keys in the other adapters, while deleting. I kind of thought that the point was to delete the tables in the correct order so you did not have to disable foreign keys ?

The problem is that in Firebird it is not possible to disable foreign keys. One can however delete them and recreate them. 

But is it not better to delete tables in the correct order ?

**Comment by jbogard** [comment]
I only delete foreign keys in the case where I detect a circular reference. So I find cycles in the graph, and disable the appropriate things to remove the cycle. For some databases, this might be disabling a constraint, for others, I disable things on the table. Each DB is a little different in its approach.

**Comment by Jeern** [comment]
Ah yes of course. I see... For MySql you disable all constraint checks, but for the rest you only disable triggers for those with Circular references. I will try to find the best way for Firebird
