### ISSUE TITLE
Question: Checkpoints surviving process restarts

### ISSUE THREAD

**Issue by DannyMeister** [jbogard/Respawn#49]
We unfortunately have a large number of integration tests which recycle an ASP.NET application pool mid test for testing configuration changes.  Can a Respawn Checkpoint be serialized or saved in some fashion to be used on the new process at the end of the test?

**Comment by jbogard** [comment]
What now? Why is Respawn running in ASP.NET?

**Comment by jbogard** [comment]
No there's not a facility to do so, sorry!

**Comment by DannyMeister** [comment]
We've tried the library now and I understand why there may have been initial confusion on my question.  I thought serializing state would be necessary because I was under the impression that the library saved the current state of the database, not reset it to empty.  It means I'll have to mix methodologies here and also maintain scripts for data insertion, as our "clean state" for this application has pre populated rows.

We still may end up being interested in serializing the graph if it saves us a lot of time for the deletion stage of database resets.

**Comment by jbogard** [comment]
Yep, the checkpoint is based on some static tables to be left alone and transactional tables to be cleared.

True checkpoints, based on my testing with SQL Server, are veeeeeery slow.
