### ISSUE TITLE
Respawn reset wipes the database

### ISSUE THREAD

**Issue by pgobbato** [jbogard/Respawn#53]
Hello!

I am setting up some tests in a similar paradigm as outlined by you in your article about subcutaneous tests. Calling Respawn's Reset is wiping my entire database.

The connection string that I use to create is the same I use to reset it and it's a SQL db.

```
[Theory, AutoData]
public async void Should_GetAnEventById(Create.Parameter eventParam)
{
    //Arrange
    var newCheckpoint = new Checkpoint();
    var eventId = await CreateEvent(eventParam);

    //Act
    var result = await Mediator.Send(new GetEventRequest(eventId));

    //Assert
    //Some asserts here
    await newCheckpoint.Reset(ConnectionString.Value.ConnectionString);
}
```
I expected the checkpoint to save a snapshot of the database, so to speak, and then be able to revert to it. Instead it is wiped entirely. The test passes.  

Am I doing something wrong?  Apologies if this is not a good avenue to ask this.  Thanks for your time!

**Comment by jbogard** [comment]
Respawn does not snapshot. It resets it to blank.

**Comment by pgobbato** [comment]
Hah!  Gotcha.  Thanks for the swift reply!

**Comment by floreseken** [comment]
Initially I had the same thought. The name 'checkpoint' is somewhat misleading IMHO

**Comment by jbogard** [comment]
I’m open to a better name. I had a hard time with it honestly.

**Comment by floreseken** [comment]
It's more a configuration than a checkpoint, so I guess something like: RespawnConfig?

**Comment by cervengoc** [comment]
+1 for naming it `RespawnConfiguration`. Very misleading indeed, completely caught me off-guard, expected that "check-point" is really what it means.

**Comment by MichelJansson** [comment]
+1 for naming it `RespawnConfiguration` here too. I guess it's time to go and rebuild my db 😅
