### ISSUE TITLE
Version 3.1.0 cannot see TablesToInclude in Checkpoint class

### ISSUE THREAD

**Issue by slamballx** [jbogard/Respawn#54]
I can't use TablesToInclude property of Checkpoint class with NuGet package 3.1.0, but i can downloading source code and referencing directly Respawn.dll.
I try also package 3.0.1 and 3.0.0 without success.

**Comment by jbogard** [comment]
I had an open PR but didn't get the changes in. I'm pushing out version 3.2.0 today, should be on NuGet in a few minutes.

**Comment by slamballx** [comment]
Great! Thank you
