### ISSUE TITLE
Adding Oracle Support

### ISSUE THREAD

**Issue by akamud** [jbogard/Respawn#6]
Some friends and I started adding support for Oracle [(link)](https://github.com/angelocarlotto/Respawn), we are almost done (3/4 tests already passing), but we hit a wall: you [can't](http://stackoverflow.com/questions/6212575/why-the-semicolon-couldnt-place-in-the-commandtext-of-a-oraclecommand-when-c-sh) execute multiple commands via DbCommand in Oracle, this means we can't truncate multiple tables in one command, so the [ExecuteDeleteSql](https://github.com/angelocarlotto/Respawn/blob/master/Respawn/Checkpoint.cs#L49) fails for Oracle.

We can't add semi-colons to the command because it will throw an invalid character error (ORA-00911). From our research we couldn't find any way to avoid this and run multiple `truncate` statements. So now we want to know if you are interested in making some changes to make this work, as that would mean having something like a `ExecuteDeleteSql` that allowed multiple commands instead of just one.

**Comment by akamud** [comment]
Any feebback on this @jbogard ?

**Comment by jbogard** [comment]
Looking at it now! The biggest hurdle was the tests.
