### ISSUE TITLE
Remove dependency to System.Data.SqlClient

### ISSUE THREAD

**Issue by kvpt** [jbogard/Respawn#67]
Hi,

There are now two SqlClient from some time now, see this [link](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/).
- The old : System.Data.SqlClient 
- The new : Microsoft.Data.SqlClient

Now that most NetCore projects use Microsoft.Data.SqlClient this create warning MSB3277 with System.Data.SqlClient at build time, but it works at runtime.

Some library like Dapper or EntityFrameworkCore are agnostic to that and don't force to use one of them.
Respawn mainly use DbConnection that is referenced in [System.Data.Common](https://www.nuget.org/packages/System.Data.Common/)

The only place where the SqlClient is needed is to instantiate a SqlConnection from a connection string [here](https://github.com/jbogard/Respawn/blob/10df2ae6040eb1985986338bb4d4c2e1620598f6/Respawn/Checkpoint.cs#L32).

So either this overload need to be removed in the next major version or the connection need to be initialized by reflection.

**Comment by jbogard** [comment]
I still like that it passes in the connection string, that's a bit more convenient. However, it's not a big deal to pass in a connection.

**Comment by kvpt** [comment]
Yes I will make a PR for that.
The more I think about this issue, the more I think the best solution is to remove this overload.
Because the library is compatible with many database providers but this overload is only compatible with SqlServer.
