### ISSUE TITLE
Keyword not supported: 'port' for MySQL Connection string

### ISSUE THREAD

**Issue by ARM-Source** [jbogard/Respawn#75]
When passing a MySQL connection string with the port identifier we get the error:

Keyword not supported: 'port'
![image](https://user-images.githubusercontent.com/59363738/98243322-0c68f200-1f6e-11eb-8310-8e93257ee08a.png)

This happens even though I specified 

`_checkpoint = new Checkpoint()
            {
                DbAdapter = DbAdapter.MySql,
                TablesToIgnore = new [] { "__EFMigrationsHistory" }
            };`

Heres how I fixed it
![image](https://user-images.githubusercontent.com/59363738/98243343-14c12d00-1f6e-11eb-84f1-e4f539f7ab31.png)
`public class RespawnMySql : Checkpoint
    {
        public override async Task Reset(string connectionString)
        {
            using (MySqlConnection connection = new MySqlConnection(connectionString))
            {
                await connection.OpenAsync();
                await base.Reset((DbConnection) connection);
            }
        }
    }`

**Comment by Michael-List** [comment]
Having the same issue with an .net 5.0 project

**Comment by branpres** [comment]
So, I've got two MySQL schemas on my local server, one for an API and one for integration tests. I had to do a similar thing as OP did. However, when Reset is called, it's executing the delete script on BOTH databases, which is not ideal. When debugging the test, the connection string being used is clearly the test database connection string. So, I'm at a loss as to what I'm doing wrong or if this is a bug (maybe not with Respawn). Anyone else have this issue?

**Comment by Dave-Townsend** [comment]
I got the same issue about port keyword not supported but for me it’s Postgresql. I need the port in connection string as it’s integration testing so I spin up lots of Docker contains with the port being the differentiator. The workaround by arm-source worked but it is a bug as port is perfectly valid in a postgresql connection string.

**Comment by borisStanojevic** [comment]
The same issue happens when using Npgsql driver.

**Comment by Dave-Townsend** [comment]
> 

Hi just on the Npgsql driver the answer is just change the way on making the connection. When I read the documentation a bit more if its not SQL server you just need to change things a bit around the connection. What I did was below works perfectly. So the secret is  make the connection with NpsqlConnectionm open it and then Checkpoint.Reset it. All your problems will go away.

public static async Task Respawn(string connectionString)
    {
        await using var conn = new NpgsqlConnection(connectionString);
        await conn.OpenAsync();
        await Checkpoint.Reset(conn);
    }

**Comment by BobaFett58** [comment]
You don't need port key actually
server=localhost,3306; works for me.
