### ISSUE TITLE
Temporal Tables and Azure SQL

### ISSUE THREAD

**Issue by Tsanton** [jbogard/Respawn#86]
Evening,

I'm having some issues using Respawn due to the fact that Azure SQL is running on SQL Server Major Version 12.x.
The issue arises due to the utilizing of temporal tables (which apply to SQL Server 2016 (13.x+), Azure SQL Database & Azure SQL Managed Instance), and that we're using actual Az DBs in our build tests and not containerized DBs.

Setting CheckTemporalTables = true is unfortunately overridden in DoesDbSupportTemporalTables due to SQL version:
```
private bool DoesDbSupportsTemporalTables(DbConnection connection)
{
      if (! DbAdapter.SupportsTemporalTables) return false;
      
      const int SqlServer2016MajorBuildVersion = 13;
      var serverVersion = connection.ServerVersion;
      var serverVersionDetails = serverVersion.Split(new[] { "." }, StringSplitOptions.None);
      var versionNumber = int.Parse(serverVersionDetails[0]);
      return versionNumber >= SqlServer2016MajorBuildVersion;
}
```
I'm not sure what the preferred fix would be: create a AzureSqlServer DbAdapter or adding additional flow control logic to the DoesDbSupportsTemporalTables method?

I can tell that manually disabling ("ALTER TABLE base.XXX SET ( SYSTEM_VERSIONING = OFF )") prior to running my tests and then reenabling (ALTER TABLE base.XXX SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = base.XXXHistory)) works without any problems. Unfortunately these manual actions do defeats the purpose of automated testing and it alters the environment for the integration testing in a significant way.

Hoping somebody with more knowledge of the code is able to come with a good fix for this issue.

**Comment by ErikEJ** [comment]
Your check is wrong, this is the correct check:

return _compatibilityLevel >= 130 && _engineEdition != 6;

https://github.com/dotnet/efcore/blob/252ece7a6bdf14139d90525a4dd0099616a82b4c/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs#L1293

**Comment by gebirgslok** [comment]
Hi all,

first: great lib! Thank you for that.

I think the `DoesDbSupportsTemporalTables` method is specific to the SQL Server `IDbAdapter` and should not be part of the DB agnostic `Checkpoint` class. I would recommend to replace the `IDbAdapter.SupportsTemporalTables` property by a `IDbAdapter.CheckSupportsTemporalTables(DbConnection connection)` method and utilize it in the checkpoint. 

I can create a PR if you like.

In that turn I can also replace the incorrect check by the one posted by @ErikEJ and with that the SQL Adapter will support temporal tables of Azure SQL as well.

Best
Jens

**Comment by jbogard** [comment]
@gebirgslok that works for me, I wasn't too familiar with the temporal tables stuff.

**Comment by RickD101** [comment]
Hi everyone, just wanted to check on the progress of this issue, will it be resolved anytime soon?

**Comment by jbogard** [comment]
Ah I see the PR. I'll check it out
