### ISSUE TITLE
reseedSql for table names with a dot in the name does not work properly

### ISSUE THREAD

**Issue by FolkertVreeken** [jbogard/Respawn#87]
Solution is in my opinion: add square brackets around schema and table name in the sql comment, like:

     -- reseed the identity only on tables that actually have had a value, otherwise next value will be off-by-one   			            
     -- https://stackoverflow.com/questions/472578/dbcc-checkident-sets-identity-to-0                                                      
        if (@DoReseed is not null)                                                                                                         
           SET @SQL = N'DBCC CHECKIDENT(''[' +  @Schema + '].[' + @TableName + ']'', RESEED, ' + Convert(varchar(max), @IdentityInitialSeedValue - 1) + ')' 
        else

**Comment by FolkertVreeken** [comment]
Additional info for SqlServerDbAdapter.cs:

Line 129 should contain IDENT_SEED('[' + OBJECT_SCHEMA_NAME(t.object_id, db_id()) + '].[' + t.name + ']') as identityInitialSeedValue

Line 142 should contain: SET @SQL = N'DBCC CHECKIDENT(''[' +  @Schema + '].[' + @TableName + ']'', RESEED, ' + Convert(varchar(max), @IdentityInitialSeedValue - 1) + ')'

**Comment by jbogard** [comment]
Wanna give a go at a PR?

**Comment by Reikooters** [comment]
Rather than hardcoding the square brackes, the correct fix would be to use the QUOTENAME() function in MSSQL as this is what should be used for sanitizing inputs for dynamic sql in this way. This will also escape square brackets in case the table name has square brackets.

Example dynamic sql:

```sql
declare @tablename VARCHAR(50) = 'Customer Data'
declare @sql VARCHAR(100) = 'SELECT * FROM ' + QUOTENAME(@tablename)
execute (@sql)
```

Value of `@sql` in the above will be `SELECT * FROM [Customer Data]`

**Comment by jbogard** [comment]
Oh that's interesting, I didn't know of that function. I wonder if the other DBs have that to make things safer.

**Comment by jbogard** [comment]
However, this would be a pretty big change, as it would now need to parameterize all schemas/tables etc.
