### ISSUE TITLE
Connection string error

### ISSUE THREAD

**Issue by DejanMilicic** [jbogard/Respawn#9]
When following connection string

.\SQLEXPRESS;Database=MyDb;Integrated Security=SSPI

I am getting following error

Format of the initialization string does not conform to specification starting at index 0.

NB: My application is using identical connstring to access database without any problems

**Comment by jbogard** [comment]
Shouldn't the connection string be:

`Server=.\SQLEXPRESS;Database=MyDb;Integrated Security=SSPI`

http://www.connectionstrings.com/sql-server/

? You're missing the "Server=" part at the beginning. I just use the standard ADO.NET provider, so I have no idea why yours would work.

**Comment by DejanMilicic** [comment]
Exactly, my bad. Sorry.
