### ISSUE TITLE
Consider targeting .NET Standard 2.0

### ISSUE THREAD

**Issue by mookid8000** [jbogard/Respawn#92]
Targeting .NET Standard 2.1 prevents Respawn from being used in .NET Framework, since .NET Standard 2.1 is only implemented on .NET Core 3.0 and later frameworks.

Maybe it would be a good idea to target .NET Standard 2.0 instead? This will make it possible for Respawn 5 to be used on .NET Framework too.

Only a few things would have to be changed in the code: 

* `await using` should be `using` (because there's no `IAsyncDisposable` in .NET Standard 2.0
* A few methods are missing async versions and must use sync (e.g. `connection.BeginTransactionAsync()`
* `HashCode` class is not available, and so it's necessary to manually compute the hash of `Schema` and `Name` in the `Table` class

but since the asyncness of these things is probably not critical, I believe it could work. 🙂 

(I'll submit a PR in a few seconds with these changes applied – feel free to reject it if you don't feel like accepting this "downgrade"*)

---

*) Yeah it's a "downgrade" in a sense, but I think it's a good thing to avoid narrowing the reach of the library.

**Comment by jbogard** [comment]
So the main motivation for dropping `netstandard2.0` is I don't want to support .NET 4.6.1 (which is typically necessary). So I could just support `netstandard2.0` but then I would get issues complaining about NuGet failures and the like. So I said "meh", my laptop can't run .NET 4.x anyway.

**Comment by mookid8000** [comment]
Oh... but what do you mean by "NuGet failures"?

**Comment by jbogard** [comment]
It's NuGet and runtime failures, see the guidance here: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

Basically the best thing you can do is drop support for .NET 4.6.1 in favor of .NET 4.7 but that's easier said than done.

**Comment by mookid8000** [comment]
I've read your link above, and I've bingled around a bit... from what I can tell, there's some magic going on in relation with System.Net.Http that can cause runtime failures (which I can recall having fought with myself, too), but other than that I can't seem to find anything. Did you experience anything in relation to Microsoft.Data.SqlClient?
