### ISSUE TITLE
Respawn and .NET 6 IConfiguration object with connection string

### ISSUE THREAD

**Issue by crega** [jbogard/Respawn#96]
Hello!
I have integration tests that are in .NET 6 
I have a method that has `Checkpoint` object as argument as well as `IConfiguration` object as argument.
So we have access to `IConfiguration` object which holds connection string towards db.

I have tried both ways to initiate reseting db.
One with name of connetion string, which on `checkpoint.Reset(nameOfConnectionString` does nothing,
and another where I create SQL connection and open it, after that i pass connection to `checkpoint.Reset(sqlConnection)` and that method call only generates SQL query for fetching db tables that i enlisted to include in reset, nothing after that.

What is the problem ?

**Comment by jbogard** [comment]
Did you await the `Reset` call?

**Comment by crega** [comment]
OMG! I totally overlooked that `Reset` method returns `Task` and not `void` ...
I am so embarrassed right now...

Well I will leave this "Issue" here in case someone does the same beginners error as myself....
@jbogard  thank you for a quick help, keep up the good work!

**Comment by jbogard** [comment]
Yes it's one of the unfortunate downsides of calling it `Reset` and not `ResetAsync`. No worries!

**Comment by Roberciiik** [comment]
Hi, do you plan to rename it to `ResetAsync` in a next release as it is a common naming pattern? I ran into a similar problem when `Reset` was not awaited.

**Comment by jbogard** [comment]
Nope, I don't.
