### ISSUE TITLE
Use `TRUNCATE TABLE` with Sql Server

### ISSUE THREAD

**Issue by giggio** [jbogard/Respawn#97]
If we truncate the tables the performance should be better, as no logs are written.

See:
https://docs.microsoft.com/en-us/sql/t-sql/statements/truncate-table-transact-sql?view=sql-server-2016

It is supported in all supported Sql Server versions.

**Comment by giggio** [comment]
My understanding is that all we need is to change this line, right?
https://github.com/jbogard/Respawn/blob/7e3548b78f7301c59bbc9a10be1b3e804cde8198/Respawn/SqlServerDbAdapter.cs#L194

**Comment by ErikEJ** [comment]
Truncate table requires elevated rights and all constraints must be removed.

**Comment by badsyntax** [comment]
The README mentions truncation:

> In benchmarks, a deterministic deletion of tables is faster than truncation, since truncation requires disabling or deleting foreign key constraints.

Also the blog post touches on truncation vs deletion: https://lostechies.com/jimmybogard/2013/06/18/strategies-for-isolating-the-database-in-tests/

Based on the research and benchmarks the maintainer has performed, DELETE seems like the faster approach.
