### ISSUE TITLE
Respawn Not Clearing Azure Databases

### ISSUE THREAD

**Issue by TehilaF** [jbogard/Respawn#98]
I'm setting up integration tests and I'd like to use the respawn library to intelligently clear out any data inserted during tests. My code is running against Azure databases. When I run a test the relevant reset code is being hit (I set breakpoints and confirmed that) but the database isn't being cleared. I confirmed that the connection string is correct.
I'm not seeing any error message.
Any insight would be very helpful! Does the Respawn library work with Azure databases?

```
[Trait("Category", "Integration")]
    public abstract class IntegrationTestBase : IClassFixture<ApiWebApplicationFactory>
    {
        protected readonly ApiWebApplicationFactory _factory;
        protected readonly ITestOutputHelper _testOutputHelper;
        protected readonly HttpClient _client;
        private readonly Checkpoint _checkpoint = new ()
        {
            WithReseed = true,
        };

        public IntegrationTestBase(ApiWebApplicationFactory fixture, ITestOutputHelper testOutputHelper)
        {

            _factory = fixture;
            _testOutputHelper = testOutputHelper;
            _client = _factory.CreateClient();
            _client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("IntegrationTest");
            _testOutputHelper = testOutputHelper;
            _checkpoint.Reset(_factory.Configuration.GetConnectionString("DB_CONN"));
        }
    }
```

**Comment by jbogard** [comment]
This is no ones fault but my own but...`Reset` is async. You have to `await` it, which means you can't use a constructor. You have to use...`IAsyncLifetime`? in XUnit.

**Comment by TehilaF** [comment]
Thanks for your response. I didn't get a chance to implement this yet but I'm hoping to asap

**Comment by jbogard** [comment]
I've renamed the methods in the next release to make it more clear. Lesson learned!
